# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\worksrc\VSCODE_PROJ\PythonCode\ToolsBox\PyQt5BoxWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        self.PyQt5BoxWindow = QtWidgets.QWidget(MainWindow)
        self.PyQt5BoxWindow.setObjectName("PyQt5BoxWindow")
        MainWindow.setCentralWidget(self.PyQt5BoxWindow)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
